config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :instructors, controllers: { sessions: 'instructors/sessions/sessions' }
  devise_for :students, controllers: { sessions: 'students/sessions/sessions' }
  resources :students, only: [:show]
  resources :instructors, only: [:show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'
  get 'about_us', to: 'static#about_us', as: :about_us
  get 'faq', to: 'static#faq', as: :faq

  resources :courses do
    resources :materials
    resources :assignments do
      resources :submissions do
        member do
          patch :score
        end
      end
    end
  end

  resources :forum_threads do
    resources :forum_posts, except: [:show]
  end
  resources :enrollments
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_instructor!, except: %i[index show]

  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
    @materials = Material.where(course_id: @course.id)

    return unless current_student && current_student.enrollments.exists?(course: @course)

    @enrollment = Enrollment.find_by(student_id: current_student.id, course_id: @course.id)
    @enrollment_id = @enrollment.id
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    @course.instructor_id = current_instructor.id
    if @course.save!
      redirect_to course_path(@course)
    else
      render :new
    end
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])
    course_id = @course.id

    if current_instructor == @course.instructor
      if @course.update(course_params)
        flash[:notice] = 'Course has been updated'
        redirect_to course_path(params[:id])
      else
        flash[:notice] = 'Failed to update Course'
        render :edit
      end
    else
      flash[:notice] = 'You are not authorized to edit this Course'
      redirect_to course_path(course_id)
    end
  end

  def destroy
    course = Course.find(params[:id])
    course_id = course.id

    if current_instructor == course.instructor
      flash[:notice] = if course.destroy
                         'Course has been deleted'
                       else
                         'Failed to delete the course'
                       end
    else
      flash[:notice] = 'You are not authorized to delete this Course'
      redirect_to course_path(course_id)
    end
    redirect_to courses_path
  end

  private

  def course_params
    params.require(:course).permit(:name, :description)
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/edit.html.erb
<div class="my-4 flex flex-col items-center">
  <h1 class="text-4xl">
    <b>
      Edit Course
    </b>
  </h1>
  <%= form_with(model: @course, url: course_path(@course.id), method: :patch) do |form| %>
    <div class="my-2">
      <%= form.label :name, class: "form-label" %><br />
      <%= form.text_field :name, placeholder: @course.name, class: "fill-none text-white border rounded-xl border-white" %>
    </div>

    <div class="my-2">
      <%= form.label :description, class: "form-label" %><br />
      <%= form.text_area :description, placeholder: @course.description, class: "fill-none text-white border rounded-xl border-white" %>
    </div>

    <div class="actions text-center mb-3">
      <%= form.submit "Edit Course", class: "text-white border rounded-lg border-yellow-400 hover:cursor-pointer bg-black-400 hover:bg-yellow-400 focus:ring-4 focus:outline-none focus:ring-yellow-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:hover:bg-yellow-600 dark:focus:ring-yellow-800" %>
    </div>
  <% end %>
</div>

app/views/courses/index.html.erb
<div class="my-4 flex flex-col items-center">
  <h2 class="text-4xl">
    <b>
      Courses
    </b>
  </h2>
  <div class="text-center">
    <ul>
      <% @courses.each do |course| %>
        <li class="my-2 border-b border-black hover:border-b hover:border-violet-800">
          <%= link_to course.name, course_path(course), class:"text-lg my-1" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/courses/new.html.erb
<div class="my-4 flex flex-col items-center">
  <h1 class="text-4xl">
    <b>
      New Course
    </b>
  </h1>
  <%= form_with(model: @course, url: courses_path, method: :post) do |form| %>
    <div class="my-2">
      <%= form.label :name %><br />
      <%= form.text_field :name, placeholder: "Enter name", class: "fill-none border rounded-xl border-white" %>
    </div>

    <div class="my-2">
      <%= form.label :description %><br />
      <%= form.text_area :description, placeholder: "Enter description", class: "fill-none border rounded-xl border-white" %>
    </div>

    <div class="actions text-center mb-3">
      <%= form.submit "Create Course", class: "hover:cursor-pointer text-white border rounded-lg border-yellow-400 bg-black-400 hover:bg-yellow-400 focus:ring-4 focus:outline-none focus:ring-yellow-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:hover:bg-yellow-600 dark:focus:ring-yellow-800" %>
    </div>
  <% end %>
</div>

app/views/courses/show.html.erb
<div class="my-40">
  <div id="course-info">
    <div class="title">
      <h3 class="text-3xl text-center"><b><%= @course.name %></b></h3>
    </div>
    <% if current_instructor == @course.instructor %>
      <div class="flex flex-row justify-center">
        <div class="p-2">
          <%= button_to "Edit Course", edit_course_path(@course.id), method: :get, class: "text-white border rounded-lg border-yellow-400 bg-black-400 hover:bg-yellow-400 focus:ring-4 focus:outline-none focus:ring-yellow-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:hover:bg-yellow-600 dark:focus:ring-yellow-800" %>
        </div>
        <div class="p-2">
        <%= button_to "Delete Course", course_path(@course.id), method: :delete, data: {turbo_confirm: "Are you sure you want to delete this course?"}, class: "text-white border rounded-lg border-yellow-400 bg-black-400 hover:bg-yellow-400 focus:ring-4 focus:outline-none focus:ring-yellow-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:hover:bg-yellow-600 dark:focus:ring-yellow-800" %>
        </div>
      </div>
    <% end %>
    <br>

    <div class="text-center" >
      <h5 class="text-xl" >Instructor:</h5>
      <p class="mb-3"><%= @course.instructor.name %></p>
      <h5 class="text-xl" >Description:</h5>
      <p><%= @course.description %></p>
    </div>
    <div>
    </div>
    <div class="flex flex-row justify-center my-3">
      <% if current_student && current_student.enrollments.exists?(course: @course) %>
        <div>
          <%= button_to "Unenroll", enrollment_path(@enrollment_id), method: :delete, data: {turbo_confirm: "Are you sure you want to unenroll from this course?"}, class: "text-white border rounded-lg border-yellow-400 bg-black-400 hover:bg-yellow-400 focus:ring-4 focus:outline-none focus:ring-yellow-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:hover:bg-yellow-600 dark:focus:ring-yellow-800" %>
        </div>
      <% elsif !current_student %>
      <% else %>
        <div>
          <%= button_to "Enroll", enrollments_path(enrollment: {course_id: @course.id}), method: :post, data: {turbo_confirm: "Are you sure you want to enroll"}, class: "text-white border rounded-lg border-yellow-400 bg-black-400 hover:bg-yellow-400 focus:ring-4 focus:outline-none focus:ring-yellow-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:hover:bg-yellow-600 dark:focus:ring-yellow-800" %>
        </div>
      <% end %>
    </div>
  </div>
  <br>
  <% if (current_student && current_student.enrollments.exists?(course: @course)) || (current_instructor && current_instructor == @course.instructor) %>
    <div id="course-materials" class="border rounded-xl border-violet-800 p-4 m-4">
      <h3 class="text-2xl">
        <b>
          Course Materials:
        </b>
      </h3>
      <ul>
        <% @materials.each do |material| %>
          <li class="my-2 border-b border-black hover:border-b hover:border-violet-800">
            <%= link_to material.title, course_material_path(@course.id, material.id), class:"text-lg my-1"  %>
          </li>
        <% end %>
      </ul>
      <% if (current_instructor && current_instructor == @course.instructor) %>
        <%= link_to "Add new material", new_course_material_path(@course.id), class: "text-white border rounded-lg border-yellow-400 bg-black-400 hover:bg-yellow-400 focus:ring-4 focus:outline-none focus:ring-yellow-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:hover:bg-yellow-600 dark:focus:ring-yellow-800 my-2" %>
      <% end %>
    </div>
    <br>
    <div id="course-assignments" class="border rounded-xl border-violet-800 p-4 m-4" >
      <h3 class="text-2xl">
        <b>
          Course Assignments:
        </b>
      </h3>
      <ul>
        <% @course.assignments.each do |assignment| %>
          <li class="my-2 border-b border-black hover:border-b hover:border-violet-800">
            <%= link_to assignment.title, course_assignment_path(@course.id, assignment.id), class:"text-lg my-1"  %>
          </li>
        <% end %>
      </ul>
      <% if (current_instructor && current_instructor == @course.instructor) %>
        <%= link_to "Add new assignment", new_course_assignment_path(@course.id), class:"text-white border rounded-lg border-yellow-400 bg-black-400 hover:bg-yellow-400 focus:ring-4 focus:outline-none focus:ring-yellow-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:hover:bg-yellow-600 dark:focus:ring-yellow-800 my-2" %>
      <% end %>
    </div>
  <% end %>
  <br>
  <div id="forum-threads" class="border rounded-xl border-violet-800 p-4 m-4">
    <h3 class="text-2xl">
      <b>
        Forum Threads:
      </b>
    </h3>
    <div>
      <ul>
        <% @course.forum_threads.each do |forum_thread| %>
          <li class="my-2 border-b border-black hover:border-b hover:border-violet-800">
            <%= link_to forum_thread.title, forum_thread_path(forum_thread), class:"text-lg my-1" %>
          </li>
        <% end %>
      </ul>
      <% if current_instructor == @course.instructor %>
        <div>
          <%= link_to "Create a Forum Thread", new_forum_thread_path(course_id: @course.id), class: "text-white border rounded-lg border-yellow-400 bg-black-400 hover:bg-yellow-400 focus:ring-4 focus:outline-none focus:ring-yellow-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:hover:bg-yellow-600 dark:focus:ring-yellow-800 my-2" %>
        </div>
      <% end %> 
    </div>
  </div>
</div>