config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :instructors, controllers: { sessions: 'instructors/sessions/sessions' }
  devise_for :students, controllers: { sessions: 'students/sessions/sessions' }
  resources :students, only: [:show]
  resources :instructors, only: [:show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'
  get 'about_us', to: 'static#about_us', as: :about_us
  get 'faq', to: 'static#faq', as: :faq

  resources :courses do
    resources :materials
    resources :assignments do
      resources :submissions do
        member do
          patch :score
        end
      end
    end
  end

  resources :forum_threads do
    resources :forum_posts, except: [:show]
  end
  resources :enrollments
end

app/models/forum_post.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: forum_posts
#
#  id              :bigint           not null, primary key
#  content         :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  forum_thread_id :integer
#  student_id      :integer
#
# Indexes
#
#  index_forum_posts_on_forum_thread_id  (forum_thread_id)
#  index_forum_posts_on_student_id       (student_id)
#
class ForumPost < ApplicationRecord
  belongs_to :forum_thread
  belongs_to :student

  validates :content, presence: true
end

app/controllers/forum_posts_controller.rb
class ForumPostsController < ApplicationController
  before_action :authenticate_student!, except: [:destroy]

  def create
    @forum_thread = ForumThread.find(params[:forum_thread_id])
    @forum_post = ForumPost.new(
      forum_post_params.merge(
        student_id: current_student.id,
        forum_thread_id: @forum_thread.id
      )
    )
    if @forum_post.save!
      flash[:notice] = 'Post created successfully'
      redirect_to forum_thread_path(@forum_thread)
    else
      flash[:notice] = 'Failed to create post'
      render :new
    end
  end

  def edit
    @forum_post = ForumPost.find(params[:id])
  end

  def update
    @forum_thread = ForumThread.find(params[:forum_thread_id])
    @forum_post = ForumPost.find(params[:id])

    if @forum_post.update(forum_post_params)
      flash[:notice] = 'Post has been edited'
      redirect_to forum_thread_path(@forum_thread)
    else
      flash[:notice] = 'Failed to edit post'
      render 'partial/new'
    end
  end

  def destroy
    forum_post = ForumPost.find(params[:id])
    forum_thread_id = forum_post.forum_thread_id
    flash[:notice] = if forum_post.destroy
                       'Post has been deleted'
                     else
                       'Failed to delete Post'
                     end
    redirect_to forum_thread_path(forum_thread_id)
  end

  private

  def forum_post_params
    params.require(:forum_post).permit(:content, :forum_thread_id)
  end
end

app/helpers/forum_posts_helper.rb
module ForumPostsHelper
end

app/views/forum_posts/_edit.html.erb
<div class="my-4 flex flex-col items-center">
  <%= form_with(model: locals[:forum_post], url: forum_thread_forum_post_path(@forum_thread, locals[:forum_post]), method: :patch) do |form| %>

    <div>
    <%= form.text_area :content, placeholder: locals[:forum_post].content, class: "fill-none form-control w-50 border rounded-xl border-white w-50" %>
    </div>

    <div class="actions text-center mb-3">
      <%= form.submit "Edit Post", class: "hover:cursor-pointer text-white border rounded-lg border-yellow-400 bg-black-400 hover:bg-yellow-400 focus:ring-4 focus:outline-none focus:ring-yellow-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:hover:bg-yellow-600 dark:focus:ring-yellow-800" %>
    </div>
  <% end %>
</div>

app/views/forum_posts/_forum_posts.html.erb
<div id="forum-posts" class="flex flex-col items-center min-w-100 border border-white rounded-lg p-5">
  <% @forum_thread.forum_posts.each do |forum_post| %>
    <div class="container border-b border-violet-800 my-4">
      <div class="card">
        <div class="card-body text-center" data-turbo="true">
          <p>
            <%= forum_post.content %>
          </p>
          <p>
            By: <%= forum_post.student.name %>
          </p>
          <% if current_student == forum_post.student  %>
            <button href="#"  data-controller="toggle" data-action="click->toggle#toggleEdit" class=" mb-2 text-white border rounded-lg border-yellow-400 bg-black-400 hover:bg-yellow-400 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:hover:bg-yellow-600">Edit</button>
            <div class="edit-partial hidden" data-target="toggle.editPartial">
              <%= render "forum_posts/edit", locals: { forum_post: forum_post } %>
            </div>
            <br>
          <% end %>
          <% if current_student == forum_post.student || current_instructor == forum_post.forum_thread.instructor %>
            <%= button_to "Delete", forum_thread_forum_post_path(forum_thread_id: @forum_thread.id, id: forum_post.id), method: :delete, data: {turbo_confirm: 'Are you sure?'}, class: "text-white border rounded-lg border-yellow-400 bg-black-400 hover:bg-yellow-400 focus:ring-4 focus:outline-none focus:ring-yellow-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:hover:bg-yellow-600 dark:focus:ring-yellow-800" %>
            <br>
          <% end %>
          on: <%= forum_post.created_at.strftime("%d.%m.%Y at: %H:%M") %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/forum_posts/_new.html.erb
<div class="my-4 flex flex-col items-center">
  <%= form_with(model: @forum_post, url: forum_thread_forum_posts_path(@forum_thread), local: true) do |form| %>
    <%= form.hidden_field "forum_post[forum_thread_id]", value: params[:forum_thread_id] %>
    <div>
      <%= form.label "Write your post:", class: "my-4" %><br />
      <%= form.text_area "forum_post[content]", class: "fill-none form-control w-50 border rounded-xl border-white" %>
    </div>

    <div class="actions text-center mb-3">
      <%= form.submit "Post", class: "text-white hover:cursor-pointer border rounded-lg border-yellow-400 bg-black-400 hover:bg-yellow-400 focus:ring-4 focus:outline-none focus:ring-yellow-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:hover:bg-yellow-600 dark:focus:ring-yellow-800" %>
    </div>
  <% end %>
</div>