config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :instructors, controllers: { sessions: 'instructors/sessions/sessions' }
  devise_for :students, controllers: { sessions: 'students/sessions/sessions' }
  resources :students, only: [:show]
  resources :instructors, only: [:show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'
  get 'about_us', to: 'static#about_us', as: :about_us
  get 'faq', to: 'static#faq', as: :faq

  resources :courses do
    resources :materials
    resources :assignments do
      resources :submissions do
        member do
          patch :score
        end
      end
    end
  end

  resources :forum_threads do
    resources :forum_posts, except: [:show]
  end
  resources :enrollments
end

app/models/forum_thread.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: forum_threads
#
#  id          :bigint           not null, primary key
#  description :text
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  course_id   :integer
#
# Indexes
#
#  index_forum_threads_on_course_id  (course_id)
#
class ForumThread < ApplicationRecord
  belongs_to :course
  has_many :forum_posts
  has_one :instructor, through: :course

  validates :title, presence: true
end

app/controllers/forum_threads_controller.rb
# frozen_string_literal: true

## ForumThreadsController handles the management of the Forum Threads
# for courses
##
class ForumThreadsController < ApplicationController
  before_action :authenticate_instructor!, except: %i[index show]
  before_action :check_current_instructor, only: %i[create update destroy]
  before_action :set_forum_thread, except: %i[index new create]

  def index
    @forum_threads = ForumThread.all
  end

  def show
    @forum_posts = @forum_thread.forum_posts
  end

  def new
    @forum_thread = ForumThread.new
  end

  def create
    @forum_thread = ForumThread.new(forum_thread_params)

    if @forum_thread.save!
      flash[:notice] = 'Forum Thread has been created'
      redirect_to forum_thread_path(@forum_thread.id)
    else
      flash[:notice] = 'Failed to create Forum Thread'
      render :new
    end
  end

  def edit; end

  def update
    @forum_thread = ForumThread.find(params[:id])

    if @forum_thread.update(forum_thread_params)
      flash[:notice] = 'Forum Thread has been updated successfully'
      redirect_to forum_thread_path(@forum_thread.id)
    else
      flash[:notice] = 'Failed to update Forum Thread'
      render :edit
    end
  end

  def destroy
    forum_thread = ForumThread.find(params[:id])

    if forum_thread.destroy
      flash[:notice] = 'Forum Thread has been deleted'
      redirect_to forum_threads_path
    else
      flash[:alert] = 'Failed to delete Forum Thread'
      redirect_to forum_thread_path(forum_thread.id)
    end
  end

  private

  def check_current_instructor
    course = Course.find(params[:forum_thread][:course_id])
    return if current_instructor == course.instructor

    flash[:error] = 'You are not authorized to change this forum thread'
    redirect_back(fallback_location: root_path)
  end

  def forum_thread_params
    params.require(:forum_thread).permit(:title, :description, :course_id)
  end

  def set_forum_thread
    @forum_thread = ForumThread.find(params[:id])
  end
end

app/helpers/forum_threads_helper.rb
module ForumThreadsHelper
end

app/views/forum_threads/edit.html.erb
<div class="my-4 flex flex-col items-center">
  <h1 class="text-4xl">
    <b>
      Edit Thread
    </b>
  </h1>
  <%= form_with(model: @forum_thread, url: forum_thread_path(@forum_thread.id), method: :patch) do |form| %>
    <%= form.hidden_field [:forum_thread][:course_id], value: @forum_thread.course_id %>

    <div class="my-2"><br />
      <%= form.label :title, class: "form-label"  %>
      <%= form.text_field :title, placeholder: @forum_thread.title, class: "fill-none border rounded-xl border-white" %>
    </div>

    <div class="my-2"><br />
      <%= form.label :description, class: "form-label"  %>
      <%= form.text_area :description, placeholder: @forum_thread.description, class: "fill-none border rounded-xl border-white" %>
    </div>

    <div class="actions text-center mb-3">
      <%= form.submit 'Edit Thread', class: "text-white border rounded-lg border-yellow-400 bg-black-400 hover:bg-yellow-400 focus:ring-4 focus:outline-none focus:ring-yellow-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:hover:bg-yellow-600 dark:focus:ring-yellow-800" %>
    </div>
  <% end %>
</div>

app/views/forum_threads/index.html.erb
<div id="forum-threads" class="container">
  <h3>Forum Threads</h3>
  <ul class="column-count-2">
    <% @forum_threads.each do |forum_thread| %>
      <li>
        <%= link_to forum_thread.title, forum_thread_path(forum_thread.id) %>
      </li>
    <% end %>
  </ul>
</div>

app/views/forum_threads/new.html.erb
<div class="my-4 flex flex-col items-center">
  <h1 class="text-4xl">
    <b>
      Create New Thread
    </b>
  </h1>
  <%= form_with(model: @forum_thread, url: forum_threads_path, method: :post) do |form| %>
    <%= form.hidden_field :course_id, value: params[:course_id] %>

    <div class="my-2">
      <%= form.label :title, class: "form-label" %><br />
      <%= form.text_field :title, placeholder: 'Please enter title', class: "fill-none text-black bg-none border rounded-xl border-white" %>
    </div>

    <div class="my-2">
      <%= form.label :description, class: "form-label" %><br />
      <%= form.text_area :description, placeholder: "Please enter description of thread", class: "fill-none text-black bg-none border rounded-xl border-white" %>
    </div>

    <div class="actions text-center mb-3">
      <%= form.submit 'Post Thread', class: "text-white border rounded-lg border-yellow-400 bg-black-400 hover:bg-yellow-400 focus:ring-4 focus:outline-none focus:ring-yellow-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:hover:bg-yellow-600 dark:focus:ring-yellow-800" %>
    </div>
  <% end %>
</div>

app/views/forum_threads/show.html.erb
<div class="my-4 flex flex-col items-center">
  <h1 class="text-4xl">
    <b>
      <%= @forum_thread.title %>
    </b>
  </h1>
  <div class="card-body">
    <div class="text-center">
      <p class="m-4">
        <%= @forum_thread.description %>
      </p>
      <h3 class="text-lg mt-2">
        Instructor:
      </h3>
      <p>
        <%= @forum_thread.instructor.name %>
      </p>
      <h3 class="text-lg mt-2">
        On:
      </h3>
      <p>
        <%= @forum_thread.created_at.strftime("%H:%M %d/%m/%Y") %>
      </p>
      <div class="flex justify-center">
        <% if current_instructor == @forum_thread.course.instructor %>
          <%= link_to "Edit", edit_forum_thread_path(@forum_thread.id), class: "text-white m-2 border rounded-lg border-yellow-400 bg-black-400 hover:bg-yellow-400 focus:ring-4 focus:outline-none focus:ring-yellow-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:hover:bg-yellow-600 dark:focus:ring-yellow-800" %>
          <%= button_to "Delete", forum_thread_path(@forum_thread.id, forum_thread: { course_id: @forum_thread.course.id}), method: :delete, data: { turbo_confirm: "Are you sure you want to delete this thread?" }, class: "text-white m-2 border rounded-lg border-yellow-400 bg-black-400 hover:bg-yellow-400 focus:ring-4 focus:outline-none focus:ring-yellow-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:hover:bg-yellow-600 dark:focus:ring-yellow-800" %>
        <% end %>
      </div>
    </div>
    <div class="card-text">
      <%= render partial:"forum_posts/new", locals: {forum_thread_id: @forum_thread.id} %> 
    </div>
  </div>
  <div class="min-w-100 flex-grow">
    <%= render partial: "forum_posts/forum_posts" %>
  </div>
  
</div>