config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :instructors, controllers: { sessions: 'instructors/sessions/sessions' }
  devise_for :students, controllers: { sessions: 'students/sessions/sessions' }
  resources :students, only: [:show]
  resources :instructors, only: [:show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'
  get 'about_us', to: 'static#about_us', as: :about_us
  get 'faq', to: 'static#faq', as: :faq

  resources :courses do
    resources :materials
    resources :assignments do
      resources :submissions do
        member do
          patch :score
        end
      end
    end
  end

  resources :forum_threads do
    resources :forum_posts, except: [:show]
  end
  resources :enrollments
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/assignment.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: assignments
#
#  id         :bigint           not null, primary key
#  content    :text
#  due_date   :datetime
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  course_id  :integer
#
# Indexes
#
#  index_assignments_on_course_id  (course_id)
#
class Assignment < ApplicationRecord
  belongs_to :course
  has_many :submissions

  validates :title, presence: true
  validates :content, presence: true
  validates :course_id, presence: true
  validates :due_date, presence: true
end

app/models/course.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: courses
#
#  id            :bigint           not null, primary key
#  description   :text
#  name          :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  instructor_id :bigint           not null
#
# Indexes
#
#  index_courses_on_instructor_id  (instructor_id)
#
# Foreign Keys
#
#  fk_rails_...  (instructor_id => instructors.id)
#
class Course < ApplicationRecord
  belongs_to :instructor
  has_many :enrollments
  has_many :students, through: :enrollments
  has_many :materials
  has_many :assignments
  has_many :forum_threads

  validates :name, presence: true
  validates :instructor, presence: true
end

app/models/enrollment.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: enrollments
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  course_id  :bigint           not null
#  student_id :bigint           not null
#
# Indexes
#
#  index_enrollments_on_course_id   (course_id)
#  index_enrollments_on_student_id  (student_id)
#
# Foreign Keys
#
#  fk_rails_...  (course_id => courses.id)
#  fk_rails_...  (student_id => students.id)
#
class Enrollment < ApplicationRecord
  belongs_to :student
  belongs_to :course
  has_many :submissions

  validates :student_id, presence: true
  validates :course_id, presence: true
  validates_uniqueness_of :student_id, scope: :course_id
end

app/models/forum_post.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: forum_posts
#
#  id              :bigint           not null, primary key
#  content         :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  forum_thread_id :integer
#  student_id      :integer
#
# Indexes
#
#  index_forum_posts_on_forum_thread_id  (forum_thread_id)
#  index_forum_posts_on_student_id       (student_id)
#
class ForumPost < ApplicationRecord
  belongs_to :forum_thread
  belongs_to :student

  validates :content, presence: true
end

app/models/forum_thread.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: forum_threads
#
#  id          :bigint           not null, primary key
#  description :text
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  course_id   :integer
#
# Indexes
#
#  index_forum_threads_on_course_id  (course_id)
#
class ForumThread < ApplicationRecord
  belongs_to :course
  has_many :forum_posts
  has_one :instructor, through: :course

  validates :title, presence: true
end

app/models/instructor.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: instructors
#
#  id                     :bigint           not null, primary key
#  bio                    :text
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  name                   :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_instructors_on_email                 (email) UNIQUE
#  index_instructors_on_reset_password_token  (reset_password_token) UNIQUE
#
class Instructor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  has_many :courses
  has_many :forum_threads, through: :courses
end

app/models/material.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: materials
#
#  id         :bigint           not null, primary key
#  content    :text
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  course_id  :integer
#
# Indexes
#
#  index_materials_on_course_id  (course_id)
#
class Material < ApplicationRecord
  belongs_to :course

  validates :title, presence: true
  validates :content, presence: true
end

app/models/student.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: students
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  name                   :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_students_on_email                 (email) UNIQUE
#  index_students_on_reset_password_token  (reset_password_token) UNIQUE
#
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :enrollments
  has_many :courses, through: :enrollments
  has_many :forum_posts

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
end

app/models/submission.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: submissions
#
#  id            :bigint           not null, primary key
#  content       :text
#  score         :float
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  assignment_id :integer
#  enrollment_id :integer
#
# Indexes
#
#  index_submissions_on_assignment_id  (assignment_id)
#  index_submissions_on_enrollment_id  (enrollment_id)
#
class Submission < ApplicationRecord
  belongs_to :enrollment
  belongs_to :assignment
  after_initialize :init

  validates :enrollment, presence: true
  validates :assignment, presence: true

  def init
    self.score ||= 0.0
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/forum_posts_helper.rb
module ForumPostsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/_alerts.html.erb
<div class="mt-2">
  <% flash.each do |name, type| %>
    <% puts "name:  #{name}, type:  #{type}" %>
    <% if name == "notice" %>
      <%= content_tag :div, type, :class => "p-4 border text-center font-bold rounded-lg border-green-800 text-green-600 flash_name#{name}", :role => "notice" %>
    <% elsif name == "alert" || name == "error" %>
      <%= content_tag :div, type, :class => "p-4 border text-center font-bold rounded-lg border-rose-800 text-rose-600 flash_name#{name}", :role => "alert" %>
    <% else %>
      <%= content_tag :div, type, :class => "p-4 border text-center font-bold rounded-lg border-yellow-800 text-yellow-600  flash_name#{name}", :role => "warning" %>
    <% end %>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<style type="text/css" media="all">
form {
  margin-bottom: 0;
} 
</style>
<div data-turbo="false" class="sticky inset-x-0 top-0 z-50">
  <nav class="py-3 bg-black border-b border-violet-800 flex justify-between px-4">
    <a class="mx-4 text-4xl text-white" href="#"><b>CourseGate</b></a>
    <div id="dropdown-menu">
      <button id="dropdownDefaultButton" data-dropdown-toggle="dropdown" class="text-white border rounded-lg border-yellow-400 bg-black-400 hover:bg-yellow-400 focus:ring-4 focus:outline-none focus:ring-yellow-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:bg-yellow-600 dark:hover:bg-yellow-600 dark:focus:ring-yellow-800" type="button">Dropdown button <svg class="w-2.5 h-2.5 ml-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
        </svg>
      </button>
      <div id="dropdown" class="z-10 hidden bg-black divide-y divide-yellow-400 border border-yellow-400 rounded-lg shadow w-44">
        <ul class="py-2 text-sm text-white" aria-labelledby="dropdownDefaultButton">
          <li class="text-black hover:text-white">
            <a class="text-white hover:text-white block px-4 py-2 hover:bg-gray-400 dark:hover:bg-gray-600 dark:hover:text-white" aria-current="page" href="/">Home</a>
          </li>
          <li class="text-white dark:hover:text-white">
            <%= link_to "Courses", courses_path, class:"hover:text-white block px-4 py-2 hover:bg-gray-400 dark:hover:bg-gray-600 dark:hover:text-white" %>
          </li>
          <li class="text-white hover:text-white">
            <%= link_to "About Us", :about_us, class:"hover:text-white block px-4 py-2 hover:bg-gray-400 dark:hover:bg-gray-600 dark:hover:text-white" %>
          </li>
          <li class="text-white hover:text-white">
            <%= link_to "FAQ", :faq, class:"hover:text-white block px-4 py-2 hover:bg-gray-400 dark:hover:bg-gray-600 dark:hover:text-white" %>
          </li>
          <hr class="h-px bg-yellow-400 border-0">
          <div class="flex flex-col">
            <p class="mx-3 mt-1"><b>Student Account</b></p>
              <li class="hover:bg-gray-400 dark:hover:bg-gray-600 dark:hover:text-white"><%= button_to("Profile", student_path(current_student.id), method: :get, class: "link block px-4 py-2 hover:bg-gray-400 dark:hover:bg-gray-600 dark:hover:text-white") if current_student %></li>
              <li class="hover:bg-gray-400 dark:hover:bg-gray-600 dark:hover:text-white"><%= button_to("Sign in", new_student_session_path, class:"link block px-4 py-2 hover:bg-gray-400 dark:hover:bg-gray-600 dark:hover:text-white" ) unless current_student %></li>
              <li class="hover:bg-gray-400 dark:hover:bg-gray-600 dark:hover:text-white"><%= button_to("Sign out", destroy_student_session_path, method: :delete, data: { turbo: true }, class:"link block px-4 py-2 hover:bg-gray-400 dark:hover:bg-gray-600 dark:hover:text-white" ) %></li>
              <% unless current_student %>
                <li class=" hover:bg-gray-400 dark:hover:bg-gray-600 dark:hover:text-white"><%= button_to("Sign up", new_student_registration_path, method: :get, class: "link block px-4 py-2 hover:bg-gray-400 dark:hover:bg-gray-600 dark:hover:text-white" ) %></li>
              <% end %>
              <hr class="h-px bg-yellow-400 border-0">
              <p class="mx-3 mt-1"><b>Instructor Account</b></p>
              <li class="hover:bg-gray-400 dark:hover:bg-gray-600 dark:hover:text-white"><%= button_to("Profile", instructor_path(current_instructor.id), method: :get, class: "link block px-4 py-2 hover:bg-gray-400 dark:hover:bg-gray-600 dark:hover:text-white") if current_instructor %></li>
              <li class="hover:bg-gray-400 dark:hover:bg-gray-600 dark:hover:text-white"><%= button_to("Sign in", new_instructor_session_path, class:"link block px-4 py-2 hover:bg-gray-400 dark:hover:bg-gray-600 dark:hover:text-white" ) unless current_instructor %></li>
              <li class="hover:bg-gray-400 dark:hover:bg-gray-600 dark:hover:text-white"><%= button_to("Sign out", destroy_instructor_session_path, method: :delete, class:"link block px-4 py-2 hover:bg-gray-400 dark:hover:bg-gray-600 dark:hover:text-white" ) %></li>
              <% unless current_instructor %>
                <li class="hover:bg-gray-400 dark:hover:bg-gray-600 dark:hover:text-white"><%= button_to("Sign up", new_instructor_registration_path, method: :get, class: "link block px-4 py-2 hover:bg-gray-400 dark:hover:bg-gray-600 dark:hover:text-white" ) %></li>
              <% end %>
          </div>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CourseGate</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.0.0/flowbite.min.css" rel="stylesheet" />
		<link
			href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&family=Roboto:wght@100;300;400;500;700;900&display=swap"
			rel="stylesheet"
		/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="stretched h-screen bg-black" >
    <div class="m-0 bg-black text-white h-screen" id="wrapper">
      <%= render "layouts/navbar" %>
      <%= render "layouts/alerts" %>
      <div class="" >
        <%= yield %>
      </div>
      <%= render "layouts/footer" %>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.1.1/flowbite.turbo.min.js"></script>
  </body>
</html>